name: CI Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: |
          cd backend
          uv pip install -r requirements.txt --system

      - name: Run Pre-commit
        run: |
          uv pip install pre-commit --system
          pre-commit run --all-files

      - name: Run tests
        run: |
          cd backend
          pytest --cov=backend --cov-branch --cov-report=xml tests/


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
